config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :edit]
  resources :books, only: [:new, :create, :index, :show, :edit, :destroy]
  root to: 'homes#top'
  get "/Homes/About" => "homes#about", as: "about"
  resources :users, only: [:show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :books, dependent: :destroy
        has_one_attached :profile_image
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    books_path
  end

  def after_sign_out_path_for(resource)
    about_path
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    redirect_to book_path
  end

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @books = @user.books 
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<% @books.each do |book| %>
<div>
  <%= link_to book_path(book.id) do %>
    <%= image_tag book.get_image %>
  <% end %>
  <p>投稿ユーザー画像：<%= image_tag 'no_image.jpg' %></p>
  <p>タイトル：<%= book.title %></p>
  <p>説明：<%= book.body %></p>
  <p>ユーザーネーム：<%= book.user.name %></p>
</div>
<% end %>

app/views/books/new.html.erb
<h1>画像投稿フォーム</h1>
  <%= form_with model: @book do |f| %>
    <h4>Title</h4>
      <%= f.text_field :title %>
    <h4>Opinion</h4>
      <%= f.text_area :body %>
    <%= f.submit 'Create Book' %>
  <% end %>

app/views/books/show.html.erb
<div>
  <%= image_tag @book.get_image %>
  <p>TITLE：<%= @book.title %></p>
  <p>説明：<%= @book.body %></p>
  <p>投稿ユーザー画像：<%= image_tag 'no_image.jpg' %></p>
  <p>ユーザーネーム：<%= @book.user.name %></p>
  <p>投稿日：<%= @book.created_at.strftime('%Y/%m/%d') %></p>
    <% if @book.user == current_user %>
    <%= link_to "削除", book_path(@book), method: :delete %>
  <% end %>
</div>

app/views/homes/about.html.erb
About

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <header>
        <% if user_signed_in? %>
      <li>
        <%= link_to '投稿フォーム', new_book_path %>
      </li>
      <li>
        <%= link_to 'マイページ', user_path(current_user.id) %>
      </li>
      <li>
         <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      </li>
      
    <% else %>
      <li>
        <%= link_to "新規登録", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "ログイン", new_user_session_path %>
      </li>
    <% end %>
  </header>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model: @user do |f| %>
  <label for="inputName">name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>  
  <%= f.submit "変更を保存" %>
<% end %>

app/views/users/show.html.erb
<div>
  <h3><%= @user.name %></h3>
  <%= image_tag @user.get_profile_image(100,100) %>
  <p><%= link_to "プロフィール編集", edit_user_path %></p>
</div>


<% @books.each do |book| %>
<div>
  <%= link_to book_path(book.id) do %>
    <%= image_tag book.get_image %>
  <% end %>
  <p>投稿ユーザー画像：<%= image_tag book.user.get_profile_image(100,100) %></p>
  <p>タイトル：<%= book.title %></p>
  <p>説明：<%= book.body %></p>
  <p>ユーザーネーム：<%= book.user.name %></p>
</div>
<% end %>